### ISSUE TITLE
Infinite loop for sequential parameter inputs while decoding

### ISSUE THREAD

**Issue by kovalensky** [Rhilip/Bencode#13]
If input is "ddd" or let's say "li", it will create infinite cpu & memory intensive loop.

**Comment by Rhilip** [comment]
In my test, both `ddd` and `li` in your example will not cause `create infinite cpu & memory intensive loop`, 
another ParseException like `Invalid integer format or integer overflow` will throw, 
since when no match char, the default string decode will process, then broken in those lines
```
            $digits = strpos($data, ':', $pos) - $pos;
            $len = self::checkInteger(substr($data, $pos, $digits));   // $digits: -3  $data: 'ddd' $pos: 3
```

- `\Rhilip\Bencode\Bencode::decode('ddd');`

```
PHP Fatal error:  Uncaught Rhilip\Bencode\ParseException: Invalid integer format or integer overflow:  in path_to\Bencode.php:129
Stack trace:
#0 path_to\Bencode.php(96): Rhilip\Bencode\Bencode::checkInteger()
#1 path_to\Bencode.php(66): Rhilip\Bencode\Bencode::decode()
#2 path_to\Bencode.php(66): Rhilip\Bencode\Bencode::decode()
#3 path_to\Bencode.php(66): Rhilip\Bencode\Bencode::decode()
#4 test.php(5): Rhilip\Bencode\Bencode::decode()
#5 {main}
  thrown in path_to\Bencode.php on line 129
```

- `\Rhilip\Bencode\Bencode::decode('li');`

```
PHP Fatal error:  Uncaught Rhilip\Bencode\ParseException: Invalid integer format or integer overflow:  in path_to\Bencode.php:129
Stack trace:
#0 path_to\Bencode.php(92): Rhilip\Bencode\Bencode::checkInteger()
#1 path_to\Bencode.php(84): Rhilip\Bencode\Bencode::decode()
#2 test.php(5): Rhilip\Bencode\Bencode::decode()
#3 {main}
  thrown in path_to\Bencode.php on line 129
```

However, it might be a critical bug, and we should check `$pos >= strlen($data)` before enter decode processing.

**Comment by kovalensky** [comment]
I tried the same fix yesterday, worked for the "ddd", but somehow in PHP 8.1.16 (win/64) it still loops for "li", probably some memory leak or modification in the code. Anyway, thank you.
```		
function bencode_decode($data, &$pos = 0)
		{
			$start_decode = ($pos === 0);
			if ($start_decode && (!is_string($data) || strlen($data) == 0)) {
				return null;
			}
			
			if($pos >= strlen($data)){
				return null;	
			}

			if ($data[$pos] === 'd') {
				$pos++;
				$return = [];
				while ($data[$pos] !== 'e') {
					$key = bencode_decode($data, $pos);
					$value = bencode_decode($data, $pos);
					if ($key === null || $value === null) {
						break;
					}
					if (!is_string($key)) {
						break;
					} elseif (array_key_exists($key, $return)) {
						break;
					}
					$return[$key] = $value;
				}
				ksort($return, SORT_STRING);
				$pos++;
			} elseif ($data[$pos] === 'l') {
				$pos++;
				$return = [];
				while ($data[$pos] !== 'e') {
					$value = bencode_decode($data, $pos);
					$return[] = $value;
				}
				$pos++;
			} elseif ($data[$pos] === 'i') {
				$pos++;
				$digits = strpos($data, 'e', $pos) - $pos;
				$value = substr($data, $pos, $digits);
				$return = checkInteger($value);
				$pos += $digits + 1;
			} else {
				$digits = strpos($data, ':', $pos) - $pos;
				$len = checkInteger(substr($data, $pos, $digits));
				if ($len < 0) {
					return null;
				}

				$pos += ($digits + 1);
				$return = substr($data, $pos, $len);

				if (strlen($return) != $len) {
					return null;
				}

				$pos += $len;
			}

			if ($start_decode && $pos !== strlen($data)) {
				return null;
			}
			return $return;
		}

		function checkInteger($value)
		{
			$int = (int)$value;
			if ((string)$int !== $value) {
				return;
			}
			return $int;
		}```

**Comment by Rhilip** [comment]
show me your test code and stack trace. And don't ask question about code outside this project.
You can also just ask GPT, I think it will help you.

**Comment by kovalensky** [comment]
I didn't want to bother you, on the contrary I wanted to help, the problem is fixed and probably this had nothing to do with your code, it works fine.

I'll be using it in the [tmrr](https://github.com/kovalensky/tmrr/) from the next release, although it's modified, I will reference your username in the code.

Here is my code for the reference purpose, I applied the fix, removed exception handling, modified checkInteger() function and created redundant variables:
```
function bencode_decode($data, &$pos = 0)
		{
			$data_len = strlen($data);
			$start_decode = ($pos === 0);
			if ($start_decode && (!is_string($data) || $data_len == 0)) {
				return null;
			}
			
			if($pos >= $data_len){
				return null;	
			}
			
			$currentChar = $data[$pos];
			if ($currentChar === 'd') {
				$pos++;
				$return = [];
				while ($currentChar !== 'e') {
					$key = bencode_decode($data, $pos);
					$value = bencode_decode($data, $pos);
					if ($key === null || $value === null) {
						break;
					}
					if (!is_string($key)) {
						break;
					} elseif (isset($return[$key])) {
						break;
					}
					$return[$key] = $value;
				}
				ksort($return, SORT_STRING);
				$pos++;
			} elseif ($currentChar === 'l') {
				$pos++;
				$return = [];
				while ($currentChar !== 'e') {
					$value = bencode_decode($data, $pos);
					if ($value === null) {
					break;
					}
					$return[] = $value;
				}
				$pos++;
			} elseif ($currentChar === 'i') {
				$pos++;
				$digits = strpos($data, 'e', $pos) - $pos;
				$value = substr($data, $pos, $digits);
				$return = checkInteger($value);
				if ($return < 0) {
					return null;
				}
				$pos += $digits + 1;
			} else {
				$digits = strpos($data, ':', $pos) - $pos;
				$len = checkInteger(substr($data, $pos, $digits));
				if ($len < 0) {
					return null;
				}

				$pos += ($digits + 1);
				$return = substr($data, $pos, $len);

				if (strlen($return) != $len) {
					return null;
				}

				$pos += $len;
			}

			if ($start_decode && $pos !== $data_len) {
				return null;
			}
			return $return;
		}

		function checkInteger($value)
		{
			$int = (int)$value;
			if ((string)$int !== $value) {
				return -1;
			}
			return $int;
		}
